name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CI: true

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 'stable'

    - name: Lint
      run: go vet ./...

    - name: Test
      run: go test -v -race ./...
